export default defineAppConfig({
  pages: [
    'pages/petServices/index',
    'pages/feederCertification/index',
    'pages/feederOrder/index',
    'pages/feederOrderUpload/index',
    'pages/createPet/index',
    'pages/joinGroupChat/index',
    'pages/login/index',
    'pages/mine/index',
    'pages/myAddress/index',
    'pages/myAddressAdd/index',
    'pages/myApplication/index',
    'pages/myDeposit/index',
    'pages/myInfo/index',
    'pages/myOrder/index',
    'pages/myOrderInfo/index',
    'pages/myPets/index',
    'pages/paySuccess/index',
    'pages/petAdopt/index',
    'pages/petFriendlyMap/index',
    'pages/petInfo/index',
    'pages/petServicesOrderCreate/step1/index',
    'pages/petServicesOrderCreate/step2/index',
    'pages/rechargeDeposit/index',
    'pages/varietySelection/index',
    'pages/webView/index',
    'pages/writeTextarea/index',
    'pages/nameVerify/index',
    'pages/localFeeders/index',
    'pages/feederInfo/index',
    'pages/feederComment/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    custom: true,
    list: [
      {
        pagePath: 'pages/petServices/index',
        text: '宠物服务',
      },
      {
        pagePath: 'pages/feederOrder/index',
        text: '我的订单',
      },
      {
        pagePath: 'pages/mine/index',
        text: '我的',
      },
    ],
  },
  resizable: true,
  usingComponents: {},
  requiredPrivateInfos: ['getLocation', 'chooseLocation'],
  permission: {
    'scope.userLocation': {
      desc: '你的位置信息将用于查询附近宠物友好地点',
    },
  },
});
